-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The first database migration. It creates every table, list of allowed
-- values, link between tables and safety rule described in src/db/schema/, on an empty database.
-- Generated by drizzle-kit from the schema and reviewed like code. Never edit a migration that has
-- already been applied anywhere; make a new one with npm run db:generate instead.
CREATE TYPE "public"."account_type" AS ENUM('local', 'tourist');--> statement-breakpoint
CREATE TYPE "public"."audit_action" AS ENUM('account_updated', 'account_deleted', 'points_adjusted', 'verification_approved', 'verification_rejected', 'refund_approved', 'refund_denied', 'deposit_claimed', 'deposit_released', 'promotion_changed', 'settings_changed', 'dispute_assigned', 'dispute_resolved');--> statement-breakpoint
CREATE TYPE "public"."audit_subject_type" AS ENUM('customer', 'provider', 'vehicle', 'booking', 'payment', 'platform');--> statement-breakpoint
CREATE TYPE "public"."auth_token_purpose" AS ENUM('verify_email', 'reset_password');--> statement-breakpoint
CREATE TYPE "public"."booking_status" AS ENUM('upcoming', 'active', 'completed', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."chat_sender" AS ENUM('customer', 'provider');--> statement-breakpoint
CREATE TYPE "public"."collection_method" AS ENUM('pickup', 'delivery');--> statement-breakpoint
CREATE TYPE "public"."deposit_status" AS ENUM('not_taken', 'held', 'released', 'claimed');--> statement-breakpoint
CREATE TYPE "public"."dispute_opened_by" AS ENUM('customer', 'provider');--> statement-breakpoint
CREATE TYPE "public"."dispute_status" AS ENUM('open', 'investigating', 'resolved');--> statement-breakpoint
CREATE TYPE "public"."document_review_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."fuel_type" AS ENUM('petrol', 'diesel', 'hybrid', 'electric');--> statement-breakpoint
CREATE TYPE "public"."island_side" AS ENUM('dutch', 'french');--> statement-breakpoint
CREATE TYPE "public"."kyc_provider" AS ENUM('stripe_identity', 'persona', 'veriff', 'didit');--> statement-breakpoint
CREATE TYPE "public"."ledger_kind" AS ENUM('charge', 'refund', 'payout', 'commission');--> statement-breakpoint
CREATE TYPE "public"."ledger_status" AS ENUM('succeeded', 'pending', 'failed');--> statement-breakpoint
CREATE TYPE "public"."listing_status" AS ENUM('live', 'pending_review', 'suspended');--> statement-breakpoint
CREATE TYPE "public"."notification_kind" AS ENUM('booking_confirmed', 'payment', 'pickup_reminder', 'return_reminder', 'late_return', 'cancellation', 'verification', 'promotion');--> statement-breakpoint
CREATE TYPE "public"."operating_side" AS ENUM('dutch', 'french', 'both');--> statement-breakpoint
CREATE TYPE "public"."payment_status" AS ENUM('paid', 'authorized', 'refunded', 'failed');--> statement-breakpoint
CREATE TYPE "public"."payout_account_status" AS ENUM('not_started', 'pending', 'active', 'restricted');--> statement-breakpoint
CREATE TYPE "public"."payout_entity" AS ENUM('us_llc', 'french_side', 'dutch_side');--> statement-breakpoint
CREATE TYPE "public"."payout_status" AS ENUM('paid', 'pending', 'processing');--> statement-breakpoint
CREATE TYPE "public"."promo_audience" AS ENUM('all', 'local', 'tourist', 'first_booking');--> statement-breakpoint
CREATE TYPE "public"."promo_kind" AS ENUM('percent', 'fixed');--> statement-breakpoint
CREATE TYPE "public"."promo_status" AS ENUM('active', 'scheduled', 'paused', 'expired');--> statement-breakpoint
CREATE TYPE "public"."provider_member_role" AS ENUM('owner', 'staff');--> statement-breakpoint
CREATE TYPE "public"."refund_status" AS ENUM('pending', 'approved', 'denied');--> statement-breakpoint
CREATE TYPE "public"."registration_status" AS ENUM('registered', 'not_registered', 'pending');--> statement-breakpoint
CREATE TYPE "public"."support_interaction_status" AS ENUM('drafted', 'approved', 'rejected', 'sent');--> statement-breakpoint
CREATE TYPE "public"."transmission" AS ENUM('automatic', 'manual');--> statement-breakpoint
CREATE TYPE "public"."vehicle_class" AS ENUM('economy', 'compact', 'suv', 'van', 'fourByFour', 'luxury');--> statement-breakpoint
CREATE TYPE "public"."vehicle_document_kind" AS ENUM('registration', 'insurance', 'roadworthiness');--> statement-breakpoint
CREATE TYPE "public"."vehicle_type" AS ENUM('car', 'atv', 'boat', 'bike');--> statement-breakpoint
CREATE TYPE "public"."verification_status" AS ENUM('unstarted', 'pending', 'approved', 'rejected', 'resubmit');--> statement-breakpoint
CREATE TABLE "auth_tokens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid NOT NULL,
	"purpose" "auth_token_purpose" NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "credentials" (
	"customer_id" uuid PRIMARY KEY NOT NULL,
	"password_hash" text NOT NULL,
	"email_verified_at" timestamp with time zone,
	"failed_login_count" integer DEFAULT 0 NOT NULL,
	"locked_until" timestamp with time zone,
	"password_changed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"account_type" "account_type" NOT NULL,
	"verification_status" "verification_status" DEFAULT 'unstarted' NOT NULL,
	"selfie_done" boolean DEFAULT false NOT NULL,
	"license_done" boolean DEFAULT false NOT NULL,
	"identity_doc_done" boolean DEFAULT false NOT NULL,
	"verification_reason" text,
	"verification_submitted_at" timestamp with time zone,
	"is_islander" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "customers_email_lowercase" CHECK ("customers"."email" = lower("customers"."email"))
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid NOT NULL,
	"token_hash" text NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"idle_expires_at" timestamp with time zone NOT NULL,
	"absolute_expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"user_agent" text,
	"ip_address" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "provider_business_profiles" (
	"provider_id" uuid PRIMARY KEY NOT NULL,
	"legal_name" text NOT NULL,
	"contact_email" text NOT NULL,
	"website" text,
	"registration_status" "registration_status" DEFAULT 'pending' NOT NULL,
	"registered_in" text,
	"registration_number" text,
	"fleet_size_band" text DEFAULT '' NOT NULL,
	"locations" text[] DEFAULT '{}'::text[] NOT NULL,
	"operating_side" "operating_side" NOT NULL,
	"owner_name" text NOT NULL,
	"owner_phone" text NOT NULL,
	"api_connected" boolean DEFAULT false NOT NULL,
	"api_last_synced_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "provider_members" (
	"provider_id" uuid NOT NULL,
	"customer_id" uuid NOT NULL,
	"role" "provider_member_role" DEFAULT 'staff' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "provider_members_provider_id_customer_id_pk" PRIMARY KEY("provider_id","customer_id")
);
--> statement-breakpoint
CREATE TABLE "provider_payout_accounts" (
	"provider_id" uuid PRIMARY KEY NOT NULL,
	"stripe_account_id" text,
	"status" "payout_account_status" DEFAULT 'not_started' NOT NULL,
	"outstanding" text[] DEFAULT '{}'::text[] NOT NULL,
	"payouts_enabled" boolean DEFAULT false NOT NULL,
	"country" text DEFAULT 'SX' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "providers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_name" text NOT NULL,
	"side" "island_side" NOT NULL,
	"town" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"responds_in" text DEFAULT '' NOT NULL,
	"delivers_vehicles" boolean DEFAULT false NOT NULL,
	"airport_pickup" boolean DEFAULT false NOT NULL,
	"is_verified" boolean DEFAULT false NOT NULL,
	"verification_status" "verification_status" DEFAULT 'unstarted' NOT NULL,
	"rating" double precision DEFAULT 0 NOT NULL,
	"review_count" integer DEFAULT 0 NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vehicle_accident_records" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"occurred_on" date NOT NULL,
	"description" text NOT NULL,
	"repaired" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vehicle_documents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"kind" "vehicle_document_kind" NOT NULL,
	"status" "document_review_status" DEFAULT 'pending' NOT NULL,
	"storage_key" text NOT NULL,
	"file_name" text NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" date,
	"reason" text,
	"reviewed_by_staff_id" uuid,
	"reviewed_at" timestamp with time zone,
	CONSTRAINT "vehicle_documents_rejection_reason" CHECK ("vehicle_documents"."status" <> 'rejected' or "vehicle_documents"."reason" is not null)
);
--> statement-breakpoint
CREATE TABLE "vehicle_photos" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"storage_key" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vehicles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"provider_id" uuid NOT NULL,
	"type" "vehicle_type" DEFAULT 'car' NOT NULL,
	"make" text NOT NULL,
	"model" text NOT NULL,
	"year" integer NOT NULL,
	"trim" text,
	"vehicle_class" "vehicle_class" NOT NULL,
	"transmission" "transmission" NOT NULL,
	"fuel" "fuel_type" NOT NULL,
	"seats" integer NOT NULL,
	"doors" integer NOT NULL,
	"air_conditioning" boolean DEFAULT true NOT NULL,
	"daily_rate_cents" integer NOT NULL,
	"weekly_rate_cents" integer,
	"minimum_days" integer DEFAULT 1 NOT NULL,
	"maximum_days" integer DEFAULT 30 NOT NULL,
	"deposit_amount_cents" integer NOT NULL,
	"deposit_is_vehicle_specific" boolean DEFAULT false NOT NULL,
	"pickup_town" text NOT NULL,
	"side" "island_side" NOT NULL,
	"delivery_available" boolean DEFAULT false NOT NULL,
	"delivery_fee_cents" integer,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"rating" double precision DEFAULT 0 NOT NULL,
	"review_count" integer DEFAULT 0 NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"listing_status" "listing_status" DEFAULT 'pending_review' NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "vehicles_daily_rate_positive" CHECK ("vehicles"."daily_rate_cents" > 0),
	CONSTRAINT "vehicles_deposit_not_negative" CHECK ("vehicles"."deposit_amount_cents" >= 0),
	CONSTRAINT "vehicles_day_limits" CHECK ("vehicles"."minimum_days" >= 1 and "vehicles"."minimum_days" <= "vehicles"."maximum_days"),
	CONSTRAINT "vehicles_seats_positive" CHECK ("vehicles"."seats" > 0)
);
--> statement-breakpoint
CREATE TABLE "booking_price_lines" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"booking_id" uuid NOT NULL,
	"label" text NOT NULL,
	"amount_cents" integer NOT NULL,
	"note" text,
	"position" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bookings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"customer_id" uuid NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"provider_id" uuid NOT NULL,
	"status" "booking_status" DEFAULT 'upcoming' NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"pickup_time" text NOT NULL,
	"return_time" text NOT NULL,
	"collection" "collection_method" NOT NULL,
	"location" text NOT NULL,
	"gross_cents" integer NOT NULL,
	"commission_cents" integer NOT NULL,
	"payout_cents" integer NOT NULL,
	"total_due_today_cents" integer NOT NULL,
	"payment_status" "payment_status" DEFAULT 'authorized' NOT NULL,
	"promo_code_id" uuid,
	"agreement_signed_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "bookings_money_adds_up" CHECK ("bookings"."gross_cents" = "bookings"."payout_cents" + "bookings"."commission_cents"),
	CONSTRAINT "bookings_money_not_negative" CHECK ("bookings"."gross_cents" >= 0 and "bookings"."commission_cents" >= 0 and "bookings"."payout_cents" >= 0 and "bookings"."total_due_today_cents" >= 0),
	CONSTRAINT "bookings_dates_in_order" CHECK ("bookings"."end_date" >= "bookings"."start_date")
);
--> statement-breakpoint
CREATE TABLE "deposits" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"booking_id" uuid NOT NULL,
	"amount_cents" integer NOT NULL,
	"status" "deposit_status" DEFAULT 'not_taken' NOT NULL,
	"stripe_payment_intent_id" text,
	"authorized_at" timestamp with time zone,
	"released_at" timestamp with time zone,
	"claimed_at" timestamp with time zone,
	"claim_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "deposits_amount_positive" CHECK ("deposits"."amount_cents" > 0),
	CONSTRAINT "deposits_claim_needs_reason" CHECK ("deposits"."status" <> 'claimed' or length(trim(coalesce("deposits"."claim_reason", ''))) > 0)
);
--> statement-breakpoint
CREATE TABLE "disputes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"booking_id" uuid NOT NULL,
	"opened_by" "dispute_opened_by" NOT NULL,
	"subject" text NOT NULL,
	"detail" text NOT NULL,
	"amount_at_stake_cents" integer DEFAULT 0 NOT NULL,
	"status" "dispute_status" DEFAULT 'open' NOT NULL,
	"assigned_to_staff_id" uuid,
	"resolution_notes" text,
	"resolved_at" timestamp with time zone,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ledger_entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"booking_id" uuid,
	"kind" "ledger_kind" NOT NULL,
	"amount_cents" integer NOT NULL,
	"status" "ledger_status" NOT NULL,
	"stripe_ref" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payouts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"provider_id" uuid NOT NULL,
	"amount_cents" integer NOT NULL,
	"gross_cents" integer NOT NULL,
	"commission_cents" integer NOT NULL,
	"booking_count" integer NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"paid_on" timestamp with time zone,
	"status" "payout_status" DEFAULT 'pending' NOT NULL,
	"stripe_transfer_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payouts_money_adds_up" CHECK ("payouts"."gross_cents" = "payouts"."amount_cents" + "payouts"."commission_cents")
);
--> statement-breakpoint
CREATE TABLE "promo_codes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"kind" "promo_kind" NOT NULL,
	"value" integer NOT NULL,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"status" "promo_status" DEFAULT 'scheduled' NOT NULL,
	"usage_limit" integer,
	"used_count" integer DEFAULT 0 NOT NULL,
	"applies_to" "promo_audience" DEFAULT 'all' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promo_codes_dates" CHECK ("promo_codes"."ends_at" > "promo_codes"."starts_at"),
	CONSTRAINT "promo_codes_value_positive" CHECK ("promo_codes"."value" > 0),
	CONSTRAINT "promo_codes_percent_range" CHECK ("promo_codes"."kind" <> 'percent' or "promo_codes"."value" <= 100)
);
--> statement-breakpoint
CREATE TABLE "refund_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"booking_id" uuid NOT NULL,
	"amount_cents" integer NOT NULL,
	"reason_given" text NOT NULL,
	"status" "refund_status" DEFAULT 'pending' NOT NULL,
	"decided_by_staff_id" uuid,
	"decided_at" timestamp with time zone,
	"decision_reason" text,
	"requested_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "refund_requests_amount_positive" CHECK ("refund_requests"."amount_cents" > 0),
	CONSTRAINT "refund_requests_decision_recorded" CHECK ("refund_requests"."status" = 'pending' or ("refund_requests"."decided_by_staff_id" is not null and "refund_requests"."decision_reason" is not null))
);
--> statement-breakpoint
CREATE TABLE "reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"booking_id" uuid NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"customer_id" uuid NOT NULL,
	"rating" smallint NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "reviews_rating_range" CHECK ("reviews"."rating" between 1 and 5)
);
--> statement-breakpoint
CREATE TABLE "chat_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"thread_id" uuid NOT NULL,
	"sender" "chat_sender" NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"vehicle_id" uuid,
	"sent_at" timestamp with time zone DEFAULT now() NOT NULL,
	"read_at" timestamp with time zone,
	CONSTRAINT "chat_messages_not_empty" CHECK (length("chat_messages"."body") > 0 or "chat_messages"."vehicle_id" is not null)
);
--> statement-breakpoint
CREATE TABLE "chat_threads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid NOT NULL,
	"provider_id" uuid NOT NULL,
	"booking_id" uuid,
	"vehicle_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid NOT NULL,
	"kind" "notification_kind" NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"sent_at" timestamp with time zone DEFAULT now() NOT NULL,
	"read_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "reward_ledger" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid NOT NULL,
	"booking_id" uuid,
	"label" text NOT NULL,
	"points" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "support_interactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid,
	"from_email" text NOT NULL,
	"subject" text DEFAULT '' NOT NULL,
	"customer_message" text NOT NULL,
	"draft" text,
	"final_sent" text,
	"status" "support_interaction_status" DEFAULT 'drafted' NOT NULL,
	"was_edited" boolean DEFAULT false NOT NULL,
	"approved_by_staff_id" uuid,
	"slack_message_ts" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin_staff" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"avatar_initials" text NOT NULL,
	"password_hash" text,
	"mfa_secret_encrypted" text,
	"disabled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"staff_id" uuid NOT NULL,
	"action" "audit_action" NOT NULL,
	"subject_type" "audit_subject_type" NOT NULL,
	"subject_id" text NOT NULL,
	"subject_label" text NOT NULL,
	"field" text NOT NULL,
	"before" text NOT NULL,
	"after" text NOT NULL,
	"reason" text NOT NULL,
	CONSTRAINT "audit_log_reason_required" CHECK (length(trim("audit_log"."reason")) > 0)
);
--> statement-breakpoint
CREATE TABLE "platform_settings" (
	"id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
	"commission_rate_bps" integer DEFAULT 3000 NOT NULL,
	"kyc_provider" "kyc_provider" DEFAULT 'stripe_identity' NOT NULL,
	"kyc_cost_per_check_cents" integer DEFAULT 0 NOT NULL,
	"kyc_bundled_documents" boolean DEFAULT false NOT NULL,
	"payout_entity" "payout_entity" DEFAULT 'us_llc' NOT NULL,
	"feature_flags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"rewards_config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "platform_settings_single_row" CHECK ("platform_settings"."id" = 1),
	CONSTRAINT "platform_settings_commission_range" CHECK ("platform_settings"."commission_rate_bps" between 0 and 10000)
);
--> statement-breakpoint
CREATE TABLE "rate_limits" (
	"key" text PRIMARY KEY NOT NULL,
	"count" integer NOT NULL,
	"resets_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "auth_tokens" ADD CONSTRAINT "auth_tokens_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "credentials" ADD CONSTRAINT "credentials_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provider_business_profiles" ADD CONSTRAINT "provider_business_profiles_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provider_members" ADD CONSTRAINT "provider_members_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provider_members" ADD CONSTRAINT "provider_members_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provider_payout_accounts" ADD CONSTRAINT "provider_payout_accounts_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_accident_records" ADD CONSTRAINT "vehicle_accident_records_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_documents" ADD CONSTRAINT "vehicle_documents_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_documents" ADD CONSTRAINT "vehicle_documents_reviewed_by_staff_id_admin_staff_id_fk" FOREIGN KEY ("reviewed_by_staff_id") REFERENCES "public"."admin_staff"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_photos" ADD CONSTRAINT "vehicle_photos_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "booking_price_lines" ADD CONSTRAINT "booking_price_lines_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_promo_code_id_promo_codes_id_fk" FOREIGN KEY ("promo_code_id") REFERENCES "public"."promo_codes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deposits" ADD CONSTRAINT "deposits_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disputes" ADD CONSTRAINT "disputes_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disputes" ADD CONSTRAINT "disputes_assigned_to_staff_id_admin_staff_id_fk" FOREIGN KEY ("assigned_to_staff_id") REFERENCES "public"."admin_staff"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_requests" ADD CONSTRAINT "refund_requests_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_requests" ADD CONSTRAINT "refund_requests_decided_by_staff_id_admin_staff_id_fk" FOREIGN KEY ("decided_by_staff_id") REFERENCES "public"."admin_staff"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_thread_id_chat_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_threads" ADD CONSTRAINT "chat_threads_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_threads" ADD CONSTRAINT "chat_threads_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_threads" ADD CONSTRAINT "chat_threads_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_threads" ADD CONSTRAINT "chat_threads_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reward_ledger" ADD CONSTRAINT "reward_ledger_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reward_ledger" ADD CONSTRAINT "reward_ledger_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_interactions" ADD CONSTRAINT "support_interactions_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_interactions" ADD CONSTRAINT "support_interactions_approved_by_staff_id_admin_staff_id_fk" FOREIGN KEY ("approved_by_staff_id") REFERENCES "public"."admin_staff"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_staff_id_admin_staff_id_fk" FOREIGN KEY ("staff_id") REFERENCES "public"."admin_staff"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "auth_tokens_token_hash_unique" ON "auth_tokens" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "auth_tokens_customer_purpose_idx" ON "auth_tokens" USING btree ("customer_id","purpose");--> statement-breakpoint
CREATE UNIQUE INDEX "customers_email_unique" ON "customers" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "sessions_token_hash_unique" ON "sessions" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "sessions_customer_idx" ON "sessions" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "provider_members_customer_idx" ON "provider_members" USING btree ("customer_id");--> statement-breakpoint
CREATE UNIQUE INDEX "provider_payout_accounts_stripe_unique" ON "provider_payout_accounts" USING btree ("stripe_account_id");--> statement-breakpoint
CREATE INDEX "vehicle_accident_records_vehicle_idx" ON "vehicle_accident_records" USING btree ("vehicle_id");--> statement-breakpoint
CREATE INDEX "vehicle_documents_vehicle_idx" ON "vehicle_documents" USING btree ("vehicle_id");--> statement-breakpoint
CREATE INDEX "vehicle_photos_vehicle_idx" ON "vehicle_photos" USING btree ("vehicle_id");--> statement-breakpoint
CREATE UNIQUE INDEX "vehicles_reference_unique" ON "vehicles" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "vehicles_provider_idx" ON "vehicles" USING btree ("provider_id");--> statement-breakpoint
CREATE INDEX "booking_price_lines_booking_idx" ON "booking_price_lines" USING btree ("booking_id");--> statement-breakpoint
CREATE UNIQUE INDEX "bookings_reference_unique" ON "bookings" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "bookings_customer_idx" ON "bookings" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "bookings_provider_idx" ON "bookings" USING btree ("provider_id");--> statement-breakpoint
CREATE INDEX "bookings_vehicle_dates_idx" ON "bookings" USING btree ("vehicle_id","start_date","end_date");--> statement-breakpoint
CREATE UNIQUE INDEX "deposits_booking_unique" ON "deposits" USING btree ("booking_id");--> statement-breakpoint
CREATE UNIQUE INDEX "disputes_reference_unique" ON "disputes" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "disputes_booking_idx" ON "disputes" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "ledger_entries_booking_idx" ON "ledger_entries" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "ledger_entries_occurred_idx" ON "ledger_entries" USING btree ("occurred_at");--> statement-breakpoint
CREATE UNIQUE INDEX "payouts_reference_unique" ON "payouts" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "payouts_provider_idx" ON "payouts" USING btree ("provider_id");--> statement-breakpoint
CREATE UNIQUE INDEX "promo_codes_code_unique" ON "promo_codes" USING btree ("code");--> statement-breakpoint
CREATE INDEX "refund_requests_booking_idx" ON "refund_requests" USING btree ("booking_id");--> statement-breakpoint
CREATE UNIQUE INDEX "reviews_booking_unique" ON "reviews" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "reviews_vehicle_idx" ON "reviews" USING btree ("vehicle_id");--> statement-breakpoint
CREATE INDEX "chat_messages_thread_idx" ON "chat_messages" USING btree ("thread_id","sent_at");--> statement-breakpoint
CREATE INDEX "chat_threads_customer_idx" ON "chat_threads" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "chat_threads_provider_idx" ON "chat_threads" USING btree ("provider_id");--> statement-breakpoint
CREATE INDEX "notifications_customer_idx" ON "notifications" USING btree ("customer_id","sent_at");--> statement-breakpoint
CREATE INDEX "reward_ledger_customer_idx" ON "reward_ledger" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "support_interactions_customer_idx" ON "support_interactions" USING btree ("customer_id");--> statement-breakpoint
CREATE UNIQUE INDEX "admin_staff_email_unique" ON "admin_staff" USING btree ("email");--> statement-breakpoint
CREATE INDEX "audit_log_at_idx" ON "audit_log" USING btree ("at");--> statement-breakpoint
CREATE INDEX "audit_log_subject_idx" ON "audit_log" USING btree ("subject_type","subject_id");--> statement-breakpoint
CREATE INDEX "rate_limits_resets_at_idx" ON "rate_limits" USING btree ("resets_at");