-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The second database migration, for taking payments. It adds Stripe's
-- reference for the rental payment and for the deposit hold, how much of a deposit was kept,
-- and the table remembering which Stripe messages have already been dealt with, so a repeated
-- one is ignored. Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TABLE "processed_webhook_events" (
	"id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "stripe_payment_intent_id" text;--> statement-breakpoint
ALTER TABLE "deposits" ADD COLUMN "claimed_amount_cents" integer;--> statement-breakpoint
CREATE UNIQUE INDEX "bookings_payment_intent_unique" ON "bookings" USING btree ("stripe_payment_intent_id");--> statement-breakpoint
CREATE UNIQUE INDEX "deposits_payment_intent_unique" ON "deposits" USING btree ("stripe_payment_intent_id");--> statement-breakpoint
ALTER TABLE "deposits" ADD CONSTRAINT "deposits_claim_within_amount" CHECK ("deposits"."claimed_amount_cents" is null or ("deposits"."claimed_amount_cents" > 0 and "deposits"."claimed_amount_cents" <= "deposits"."amount_cents"));
