-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The fourth database migration, for the staff admin panel. It adds staff
-- sign-in sessions (their own table, separate from customers'), the encrypted two-factor secret
-- and when it was set up, and the wrong-attempt counters behind the staff account lockout.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TABLE "admin_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"staff_id" uuid NOT NULL,
	"token_hash" text NOT NULL,
	"mfa_passed" boolean DEFAULT false NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"idle_expires_at" timestamp with time zone NOT NULL,
	"absolute_expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"ip_address" text,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "admin_staff" ADD COLUMN "mfa_enrolled_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "admin_staff" ADD COLUMN "failed_login_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "admin_staff" ADD COLUMN "locked_until" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "admin_staff" ADD COLUMN "last_sign_in_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "admin_sessions" ADD CONSTRAINT "admin_sessions_staff_id_admin_staff_id_fk" FOREIGN KEY ("staff_id") REFERENCES "public"."admin_staff"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "admin_sessions_token_hash_unique" ON "admin_sessions" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "admin_sessions_staff_idx" ON "admin_sessions" USING btree ("staff_id");
