-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The sixth database migration, for managing staff accounts from the admin
-- panel instead of from the server. It adds the "must set their own password first" flag, and the
-- new kinds of audit entry a staff change is recorded as. Existing accounts get false for the
-- flag, so nobody already signed in is interrupted.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
ALTER TYPE "public"."audit_action" ADD VALUE 'staff_created';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'staff_reset';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'staff_disabled';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'staff_enabled';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'password_changed';--> statement-breakpoint
ALTER TYPE "public"."audit_subject_type" ADD VALUE 'staff';--> statement-breakpoint
ALTER TABLE "admin_staff" ADD COLUMN "must_change_password" boolean DEFAULT false NOT NULL;
