-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The seventh database migration, for the three things staff can now do to a
-- rental business from the admin panel: close it, open it again, and correct its details. It adds
-- only the new kinds of audit entry those decisions are recorded as — no table changes, because
-- closing already had its column. Each ALTER TYPE is its own statement: Postgres will not let a
-- transaction use an enum value it has just added.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
ALTER TYPE "public"."audit_action" ADD VALUE 'business_closed';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'business_reopened';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'business_updated';
