-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The eighth database migration, for what each member of staff is
-- allowed to do. Until now every staff account could do everything, and the panel said so.
--
-- Three things happen here. Every account gets a tier, and new ones are administrators — the
-- everyday job, never staff management. The database itself allows only ONE godfather, because
-- a rule kept in code alone holds until somebody writes a script, and that is the account
-- nobody else can disable or demote. And the account that already exists becomes the godfather:
-- it is the one the business was set up with, and without this nobody could manage staff at all.
--
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."admin_tier" AS ENUM('godfather', 'owner', 'administrator', 'viewer');--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'staff_tier_changed';--> statement-breakpoint
ALTER TABLE "admin_staff" ADD COLUMN "tier" "admin_tier" DEFAULT 'administrator' NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "admin_staff_one_godfather" ON "admin_staff" USING btree ("tier") WHERE "admin_staff"."tier" = 'godfather';
--> statement-breakpoint
-- The account the business was set up with becomes the godfather. Written as one row by id so
-- the unique index above cannot be broken, and a no-op on an empty database (every test).
UPDATE "admin_staff" SET "tier" = 'godfather'
WHERE "id" = (SELECT "id" FROM "admin_staff" ORDER BY "created_at" ASC LIMIT 1);
