-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The ninth database migration, for saved cards: each customer gets a place
-- to keep the id of their own record at Stripe, where their saved cards live. No card detail is
-- ever stored here — only that id, and it is removed when the account closes.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
ALTER TABLE "customers" ADD COLUMN "stripe_customer_id" text;--> statement-breakpoint
CREATE UNIQUE INDEX "customers_stripe_customer_unique" ON "customers" USING btree ("stripe_customer_id");
