-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The tenth database migration, for identity checks: each customer gets a
-- place to keep the id of the check in progress at Stripe Identity. The ID photos themselves
-- stay with Stripe; only the id and the outcome are ever kept here.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
ALTER TABLE "customers" ADD COLUMN "identity_session_id" text;
