-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The thirteenth database migration, for changing a rental's dates as a request
-- the business answers; why a renter cancelled; the note a customer sees when a refund is
-- denied.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."date_change_payment_status" AS ENUM('unpaid', 'paid');--> statement-breakpoint
CREATE TYPE "public"."date_change_status" AS ENUM('pending', 'accepted', 'declined', 'withdrawn', 'expired');--> statement-breakpoint
CREATE TABLE "date_change_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"booking_id" uuid NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"from_start_date" date NOT NULL,
	"from_end_date" date NOT NULL,
	"days" integer NOT NULL,
	"from_days" integer NOT NULL,
	"total_cents" integer NOT NULL,
	"difference_cents" integer NOT NULL,
	"refund_cents" integer DEFAULT 0 NOT NULL,
	"gross_cents" integer NOT NULL,
	"commission_cents" integer NOT NULL,
	"payout_cents" integer NOT NULL,
	"lines" jsonb NOT NULL,
	"explanation" text,
	"status" date_change_status DEFAULT 'pending' NOT NULL,
	"note" text,
	"payment_status" date_change_payment_status,
	"stripe_payment_intent_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"decided_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "cancellation_reason" text;--> statement-breakpoint
ALTER TABLE "refund_requests" ADD COLUMN "customer_note" text;--> statement-breakpoint
ALTER TABLE "date_change_requests" ADD CONSTRAINT "date_change_requests_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "date_change_requests_booking_idx" ON "date_change_requests" USING btree ("booking_id");
