-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The fourteenth database migration, for each person's own options on a
-- conversation: pinned, muted, and marked unread.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TABLE "chat_thread_settings" (
	"thread_id" uuid NOT NULL,
	"customer_id" uuid NOT NULL,
	"side" "chat_sender" NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"muted" boolean DEFAULT false NOT NULL,
	"marked_unread" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chat_thread_settings_thread_id_customer_id_side_pk" PRIMARY KEY("thread_id","customer_id","side")
);
--> statement-breakpoint
ALTER TABLE "chat_thread_settings" ADD CONSTRAINT "chat_thread_settings_thread_id_chat_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_thread_settings" ADD CONSTRAINT "chat_thread_settings_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;
