-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The sixteenth database migration, for the smaller things a business's own
-- screens needed: a registration number and an answered accident question on each car, staff's
-- reason when an application is turned down, and how quickly a business replies as a code.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
ALTER TABLE "provider_business_profiles" ADD COLUMN "verification_reason" text;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "registration" text;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "accident_history_declared" boolean DEFAULT false NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "vehicles_provider_registration_unique" ON "vehicles" USING btree ("provider_id","registration") WHERE "vehicles"."deleted_at" is null and "vehicles"."registration" is not null;--> statement-breakpoint
-- Written by hand: what was already there, put into the new shape before the
-- rule below starts refusing anything else. Free English becomes the nearest
-- code; anything unrecognisable is left unset rather than guessed.
UPDATE "providers" SET "responds_in" = CASE
  WHEN lower("responds_in") LIKE '%hours%' THEN 'within_hours'
  WHEN lower("responds_in") LIKE '%hour%' THEN 'within_hour'
  WHEN lower("responds_in") LIKE '%day%' THEN 'within_day'
  ELSE ''
END
WHERE "responds_in" NOT IN ('', 'within_hour', 'within_hours', 'within_day');--> statement-breakpoint
-- A car with accidents on record has had the question answered.
UPDATE "vehicles" SET "accident_history_declared" = true
WHERE EXISTS (SELECT 1 FROM "vehicle_accident_records" WHERE "vehicle_accident_records"."vehicle_id" = "vehicles"."id");--> statement-breakpoint
ALTER TABLE "providers" ADD CONSTRAINT "providers_responds_in_known" CHECK ("providers"."responds_in" in ('', 'within_hour', 'within_hours', 'within_day'));
