-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The seventeenth database migration, for a business's own discount codes,
-- and which one a booking used.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TABLE "business_promotions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider_id" uuid NOT NULL,
	"code" text NOT NULL,
	"percent_off" integer NOT NULL,
	"min_days" integer,
	"starts_on" date,
	"ends_on" date,
	"max_uses" integer,
	"active" boolean DEFAULT true NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "business_promotions_percent_range" CHECK ("business_promotions"."percent_off" between 5 and 50),
	CONSTRAINT "business_promotions_dates" CHECK ("business_promotions"."starts_on" is null or "business_promotions"."ends_on" is null or "business_promotions"."ends_on" >= "business_promotions"."starts_on"),
	CONSTRAINT "business_promotions_limits" CHECK (("business_promotions"."min_days" is null or "business_promotions"."min_days" >= 1) and ("business_promotions"."max_uses" is null or "business_promotions"."max_uses" >= 1))
);
--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "promotion_id" uuid;--> statement-breakpoint
ALTER TABLE "business_promotions" ADD CONSTRAINT "business_promotions_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "business_promotions_code_unique" ON "business_promotions" USING btree ("provider_id","code") WHERE "business_promotions"."deleted_at" is null;--> statement-breakpoint
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_promotion_id_business_promotions_id_fk" FOREIGN KEY ("promotion_id") REFERENCES "public"."business_promotions"("id") ON DELETE set null ON UPDATE no action;
