-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The nineteenth database migration, for a business asking SXM Rentals'
-- team to set its fleet up, and the private files it sends with it.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."fleet_request_status" AS ENUM('waiting', 'done');--> statement-breakpoint
CREATE TABLE "fleet_request_files" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"request_id" uuid NOT NULL,
	"file_name" text NOT NULL,
	"content_type" text NOT NULL,
	"size_bytes" integer NOT NULL,
	"content" "bytea" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fleet_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider_id" uuid NOT NULL,
	"requested_by" uuid,
	"fleet_size" text NOT NULL,
	"record_format" text NOT NULL,
	"contact" text NOT NULL,
	"notes" text,
	"status" "fleet_request_status" DEFAULT 'waiting' NOT NULL,
	"handled_at" timestamp with time zone,
	"handled_by_staff_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "fleet_request_files" ADD CONSTRAINT "fleet_request_files_request_id_fleet_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."fleet_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fleet_requests" ADD CONSTRAINT "fleet_requests_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fleet_requests" ADD CONSTRAINT "fleet_requests_requested_by_customers_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."customers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "fleet_request_files_request_idx" ON "fleet_request_files" USING btree ("request_id");--> statement-breakpoint
CREATE INDEX "fleet_requests_status_idx" ON "fleet_requests" USING btree ("status","created_at");
