-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The twentieth database migration, for connecting a business's own rental
-- software: a hashed API key and where to send bookings; and which unavailable days that
-- software sent.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."vehicle_block_source" AS ENUM('business', 'partner');--> statement-breakpoint
CREATE TABLE "provider_integrations" (
	"provider_id" uuid PRIMARY KEY NOT NULL,
	"api_key_hash" text,
	"api_key_last4" text,
	"webhook_url" text,
	"last_synced_at" timestamp with time zone,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "vehicle_blocks" ADD COLUMN "source" "vehicle_block_source" DEFAULT 'business' NOT NULL;--> statement-breakpoint
ALTER TABLE "provider_integrations" ADD CONSTRAINT "provider_integrations_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "provider_integrations_key_unique" ON "provider_integrations" USING btree ("api_key_hash");
