-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The twenty-first database migration, for the signature a renter draws on
-- the rental agreement, which wording they agreed to, and when.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TABLE "booking_signatures" (
	"booking_id" uuid PRIMARY KEY NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"strokes" jsonb NOT NULL,
	"platform" text,
	"ip_address" text,
	"signed_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "agreement_version" text;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "agreement_drawn" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "booking_signatures" ADD CONSTRAINT "booking_signatures_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE cascade ON UPDATE no action;
