-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The twenty-third database migration, for signing in with a code sent by
-- text: when a phone number was confirmed, and the codes asked for (hashed).
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."phone_challenge_purpose" AS ENUM('sign_in', 'confirm_phone');--> statement-breakpoint
CREATE TABLE "phone_challenges" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"phone" text NOT NULL,
	"purpose" "phone_challenge_purpose" NOT NULL,
	"customer_id" uuid,
	"code_hash" text NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"ip_address" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "phone_verified_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "phone_challenges" ADD CONSTRAINT "phone_challenges_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "phone_challenges_phone_idx" ON "phone_challenges" USING btree ("phone","created_at");--> statement-breakpoint
CREATE INDEX "phone_challenges_ip_idx" ON "phone_challenges" USING btree ("ip_address","created_at");
