-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The twenty-fourth database migration, for marking a call's line in a
-- conversation as a call, with how it went.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."call_outcome" AS ENUM('answered', 'missed');--> statement-breakpoint
CREATE TYPE "public"."message_kind" AS ENUM('text', 'call');--> statement-breakpoint
ALTER TABLE "chat_messages" ADD COLUMN "kind" "message_kind" DEFAULT 'text' NOT NULL;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD COLUMN "call_outcome" "call_outcome";--> statement-breakpoint
ALTER TABLE "chat_messages" ADD COLUMN "call_minutes" integer;
