-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The twenty-fifth database migration, for holding the deposit
-- automatically on the card that paid: the customer's agreement, the saved card, how the hold
-- went, and the message when it needs them.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."deposit_auto_hold_status" AS ENUM('placing', 'placed', 'needs_customer');--> statement-breakpoint
ALTER TYPE "public"."notification_kind" ADD VALUE 'deposit_hold_needed';--> statement-breakpoint
ALTER TABLE "deposits" ADD COLUMN "hold_consent_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "deposits" ADD COLUMN "payment_method_id" text;--> statement-breakpoint
ALTER TABLE "deposits" ADD COLUMN "auto_hold_status" "deposit_auto_hold_status";--> statement-breakpoint
ALTER TABLE "deposits" ADD COLUMN "auto_hold_tried_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "deposits" ADD COLUMN "auto_hold_problem" text;
