-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The twenty-sixth database migration, for paying businesses: where each
-- one's bank is and whether Stripe or a bank transfer pays it, a payout recorded as paid by bank
-- transfer, and which Stripe mode the server last ran in.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."payout_method" AS ENUM('stripe', 'bank_transfer');--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'payout_sent';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'payout_marked_paid';--> statement-breakpoint
ALTER TABLE "provider_payout_accounts" ADD COLUMN "method" "payout_method" DEFAULT 'stripe' NOT NULL;--> statement-breakpoint
ALTER TABLE "payouts" ADD COLUMN "bank_reference" text;--> statement-breakpoint
ALTER TABLE "payouts" ADD COLUMN "paid_by_staff_id" uuid;--> statement-breakpoint
ALTER TABLE "platform_settings" ADD COLUMN "stripe_mode" text;
