-- SXM Rentals — Created by Giordano Bertin-Maurice
-- Copyright (c) 2026 Giordano Bertin-Maurice. All rights reserved.
-- WHAT THIS FILE DOES: The twenty-seventh database migration, for the admin panel's Activity
-- screen: who cancelled a booking, and when a car first went on sale, filled in for what already
-- exists where the record allows.
-- Generated by drizzle-kit from src/db/schema and reviewed like code.
-- Never edit a migration already applied anywhere; make a new one with npm run db:generate.
CREATE TYPE "public"."booking_cancelled_by" AS ENUM('customer', 'provider', 'staff');--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "listed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "bookings" ADD COLUMN "cancelled_by" "booking_cancelled_by";
--> statement-breakpoint
-- Written by hand: filling in what already exists, only where the record says so.
-- Every booking cancelled so far was cancelled by its renter: until now that
-- was the only way a booking could be cancelled. Its time was always recorded.
UPDATE "bookings" SET "cancelled_by" = 'customer' WHERE "status" = 'cancelled' AND "cancelled_by" IS NULL;--> statement-breakpoint
-- A car staff approved went on sale at its first approval, which the audit log
-- holds.
UPDATE "vehicles" SET "listed_at" = (
  SELECT min("audit_log"."at") FROM "audit_log"
  WHERE "audit_log"."subject_type" = 'vehicle'
    AND "audit_log"."subject_id" = "vehicles"."id"::text
    AND "audit_log"."action" = 'verification_approved'
)
WHERE "listed_at" IS NULL;--> statement-breakpoint
-- A car on sale with no approval on record went on sale when it was added
-- (approval was switched off). Anything else stays unknown rather than guessed.
UPDATE "vehicles" SET "listed_at" = "created_at"
WHERE "listed_at" IS NULL AND "listing_status" = 'live';
